apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner-pgl
spec:
  labels:
    Monitor-Services: "true"
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: {{ .Values.karpenter_ec2_capacity_type }}
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: {{ .Values.excluded_karpenter_ec2_instance_type }}
  providerRef:                                # optional, recommended to use instead of `provider`
    name: karpenter-node-template-pgl
  ttlSecondsAfterEmpty: 300                   # optional, but never scales down if not set
  # ttlSecondsUntilExpired: 600     # optional, but never expires if not set

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-node-template-pgl
spec:
  subnetSelector:                             # required
    Name: {{ .Values.private_subnet_name }}
  securityGroupSelector:                      # required, when not using launchTemplate
    aws:eks:cluster-name: {{ .Values.cluster_name }}
