{
 "title": "Analytics - NGINX",
 "description": "Nginx access log analytics dashboard using Promtail and Loki v2+. Prometheus datasource is created from Loki service.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Visitor Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Unique user visits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({host=\"$host\", http_user_agent !~ \".*bot.*\",  http_user_agent !~ \".*crawler.*\" , remote_addr !~ \"2001:4ca0:108:42::*\", remote_addr !=\"62.210.149.41\" , remote_addr !~ \"91.134.156.*\" , remote_addr !~ \"37.59.149.*\",  http_user_agent != \"worldping-api\" ,  request_uri !~ \"/wp-.*\" ,  request_uri !~ \"//wp-.*\" ,  request_uri !~ \"/*.wordfence.*\" ,  request_uri !~ \"/robots.txt\" ,  request_uri !~ \"/xmlrpc.php\", remote_addr!=\"\" } [1h])))",
       "legendFormat": "{{ remote_addr}}"
      }
     ]
    },
    {
     "title": "Unique user visits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({host=\"$host\", http_user_agent !~ \".*bot.*\",  http_user_agent !~ \".*crawler.*\" , remote_addr !~ \"2001:4ca0:108:42::*\", remote_addr !=\"62.210.149.41\" , remote_addr !~ \"91.134.156.*\" , remote_addr !~ \"37.59.149.*\",  http_user_agent != \"worldping-api\" ,  request_uri !~ \"/wp-.*\" ,  request_uri !~ \"//wp-.*\" ,  request_uri !~ \"/*.wordfence.*\" ,  request_uri !~ \"/robots.txt\" ,  request_uri !~ \"/xmlrpc.php\" } [1d])))"
      }
     ]
    },
    {
     "title": "Unique user visits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({host=\"$host\", http_user_agent !~ \".*bot.*\",  http_user_agent !~ \".*crawler.*\" , remote_addr !~ \"2001:4ca0:108:42::*\", remote_addr !=\"62.210.149.41\" , remote_addr !~ \"91.134.156.*\" , remote_addr !~ \"37.59.149.*\",  http_user_agent != \"worldping-api\" ,  request_uri !~ \"/wp-.*\" ,  request_uri !~ \"//wp-.*\" ,  request_uri !~ \"/*.wordfence.*\" ,  request_uri !~ \"/robots.txt\" ,  request_uri !~ \"/xmlrpc.php\", remote_addr!=\"\" } [2d])))"
      }
     ]
    },
    {
     "title": "Unique user visits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({host=\"$host\", http_user_agent !~ \".*bot.*\",  http_user_agent !~ \".*crawler.*\" , remote_addr !~ \"2001:4ca0:108:42::*\", remote_addr !=\"62.210.149.41\" , remote_addr !~ \"91.134.156.*\" , remote_addr !~ \"37.59.149.*\",  http_user_agent != \"worldping-api\" ,  request_uri !~ \"/wp-.*\" ,  request_uri !~ \"//wp-.*\" ,  request_uri !~ \"/*.wordfence.*\" ,  request_uri !~ \"/robots.txt\" ,  request_uri !~ \"/xmlrpc.php\" } [7d])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total requests  ",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(host) (count_over_time({host=\"$host\"}[$__interval]))  ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Requests per status code",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (status) (count_over_time({host=\"$host\",status!=\"\", app=\"ingress-nginx\"}[$__auto]))",
       "legendFormat": "HTTP Status {{status}} "
      }
     ]
    },
    {
     "title": "% of 5xx requests ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": " sum(rate({host=\"$host\", status=~\"5[0-9][0-9]\"}[$__interval])) / (sum(rate({host=\"$host\"} [$__interval])) / 100)"
      }
     ]
    },
    {
     "title": "% of 4xx requests ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": " sum(rate({host=\"$host\", status=~\"4[0-9][0-9]\"}[$__interval])) / (sum(rate({host=\"$host\"} [$__interval])) / 100)"
      }
     ]
    },
    {
     "title": "Total Bytes Sent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time({host=\"$host\", status=\"200\"} | unwrap body_bytes_sent [$__interval]))",
       "legendFormat": "Bytes sent"
      }
     ]
    },
    {
     "title": "Recent requests > 500 Status",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{host=\"$host\", request_uri !=\"\", \r\n http_user_agent !~ \".*bot.*\", \r\n http_user_agent !~ \".*crawler.*\", \r\n remote_addr !~ \"2001:4ca0:108:42::*\", \r\n remote_addr != \"62.210.149.41\", \r\n remote_addr !~ \"91.134.156.*\", \r\n remote_addr !~ \"37.59.149.*\", \r\n http_user_agent != \"worldping-api\", \r\n request_uri !~ \"/wp-.*\", \r\n request_uri !~ \"//wp-.*\", \r\n request_uri !~ \"/*.wordfence.*\", \r\n request_uri !~ \"/robots.txt\", \r\n request_uri !~ \"/xmlrpc.php\",\r\n status =~ \"5[0-9][0-9]\"\r\n} | line_format \"request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}}.\"\r\n"
      }
     ]
    },
    {
     "title": "Recent requests",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{host=\"$host\", request_uri !=\"\", \r\n http_user_agent !~ \".*bot.*\", \r\n http_user_agent !~ \".*crawler.*\", \r\n remote_addr !~ \"2001:4ca0:108:42::*\", \r\n remote_addr != \"62.210.149.41\", \r\n remote_addr !~ \"91.134.156.*\", \r\n remote_addr !~ \"37.59.149.*\", \r\n http_user_agent != \"worldping-api\", \r\n request_uri !~ \"/wp-.*\", \r\n request_uri !~ \"//wp-.*\", \r\n request_uri !~ \"/*.wordfence.*\", \r\n request_uri !~ \"/robots.txt\", \r\n request_uri !~ \"/xmlrpc.php\"\r\n} | line_format \"request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}}.\"\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sources & Behaviours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top IPs",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(5, sum by (remote_addr) (\r\n  count_over_time({\r\n    host=\"$host\",\r\n    remote_addr != \"\",\r\n    http_user_agent !~ \".*bot.*\",\r\n    http_user_agent !~ \".*crawler.*\",\r\n    remote_addr !~ \"2001:4ca0:108:42::*\",\r\n    remote_addr !=\"62.210.149.41\",\r\n    remote_addr !~ \"91.134.156.*\",\r\n    remote_addr !~ \"37.59.149.*\",\r\n    http_user_agent != \"worldping-api\",\r\n    request_uri !~ \"/wp-.*\",\r\n    request_uri !~ \"//wp-.*\",\r\n    request_uri !~ \"/*.wordfence.*\",\r\n    request_uri !~ \"/robots.txt\",\r\n    request_uri !~ \"/xmlrpc.php\"\r\n  } [$__interval])\r\n))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top Requested Pages - Excluding '/'",
     "type": "table",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 3 },
     "targets": [
      {
       "expr": "topk(10, sum by (request_uri) (\r\n  count_over_time({\r\n    request_uri !=\"\",\r\n    host=\"$host\",\r\n    http_user_agent !~ \".*bot.*\",\r\n    http_user_agent !~ \".*crawler.*\",\r\n    request_uri != \"/\",\r\n    request_uri !~ \"/wp-.*\",\r\n    request_uri !~ \"//wp-.*\",\r\n    request_uri !~ \"/*.wordfence.*\",\r\n    request_uri !~ \"/robots.txt\",\r\n    request_uri !~ \"/xmlrpc.php\"\r\n  }[$__interval])\r\n))\r\n",
       "legendFormat": "{{request_uri}}"
      },
      {
       "expr": "topk(10, sum by (request_uri) (\r\n  count_over_time({\r\n    request_uri = \"/health-check/\",\r\n    http_user_agent !~ \".*bot.*\",\r\n    http_user_agent !~ \".*crawler.*\",\r\n    request_uri != \"/\",\r\n    request_uri !~ \"/wp-.*\",\r\n    request_uri !~ \"//wp-.*\",\r\n    request_uri !~ \"/*.wordfence.*\",\r\n    request_uri !~ \"/robots.txt\",\r\n    request_uri !~ \"/xmlrpc.php\"\r\n  }[$__interval])\r\n))\r\n",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top HTTP Referers",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by (http_referr) (\r\n  count_over_time({\r\n    host=\"$host\",\r\n    http_user_agent !~ \".*bot.*\",\r\n    http_user_agent !~ \".*crawler.*\",\r\n    http_user_agent != \"worldping-api\",\r\n    http_referr != \"\"\r\n  } [$__interval])\r\n))\r\n",
       "legendFormat": "{{http_referr}}"
      }
     ]
    },
    {
     "title": "Top User Agents",
     "type": "table",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 14 },
     "targets": [
      {
       "expr": "topk(10, sum by (http_user_agent) (count_over_time({host=~\"$host\", http_user_agent!=\"\"} [$__interval])))",
       "legendFormat": "{{http_user_agent}}"
      }
     ]
    },
    {
     "title": "Top HTTP Referers - Exclude Panxora Site",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "topk(10, sum by (http_referr) (\r\n  count_over_time({\r\n    host=\"$host\",\r\n    http_user_agent !~ \".*bot.*\",\r\n    http_user_agent !~ \".*crawler.*\",\r\n    http_user_agent != \"worldping-api\",\r\n    http_referr != \"\",\r\n    http_referr !~ \".*?panxora.*?\",\r\n    http_referr != \"http://192.168.120.55:9000/\"\r\n  } [$__interval])\r\n))\r\n",
       "legendFormat": "{{http_referr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Statistics Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "99th percentile of Request Time by Request Uri",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (http_referr,request_uri) (quantile_over_time(0.99, {host=\"$host\", request_time!=\"\"} | unwrap request_time [$__interval]))",
       "legendFormat": "{{ http_referr}}{{request_uri}}"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (count_over_time({host=\"$host\", status!=\"\"} [$__interval]))",
       "legendFormat": "HTTP Status {{status}}"
      }
     ]
    },
    {
     "title": "Successful Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time({host=\"$host\", status=\"200\"} | unwrap body_bytes_sent [$__interval]))",
       "legendFormat": "Bytes sent"
      }
     ]
    }
   ]
  }
 ]
}