{
 "title": "AWS NAT Gateway",
 "description": "AWS NAT Gateway metrics ",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "gatewayId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "BytesInFromDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "BytesOutToSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Outgoing Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "BytesInFromSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "BytesOutToDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "PacketsInFromDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "PacketsOutToSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Outgoing Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "PacketsInFromSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "PacketsOutToDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Idle Timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "IdleTimeoutCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Packet Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "PacketsDropCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Port Allocation Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "ErrorPortAllocation",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "ConnectionAttemptCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$gatewayId" },
     "metricName": "ConnectionEstablishedCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "\n<a href=\"https://github.com/praveenchandran/grafana\" target=\"_blank\"/>Github Repo</a> | \n<a target=\"_blank\" href=\"https://github.com/praveenchandran\">Author</a> |\n<a target=\"_blank\" href=\"https://grafana.com/dashboards/16185\">Download link</a> |\n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html\">AWS Cloudwatch documentation</a>"
   }
  }
 ]
}