{
 "title": "AWS Inspector",
 "description": "Visualize AWS Inspector metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "AssessmentTargetName",
    "label": "AssessmentTargetName",
    "query": "dimension_values($region,AWS/Inspector,TotalAssessmentRuns,AssessmentTargetName)"
   }
  ]
 },
 "panels": [
  {
   "title": "TotalFindings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "AssessmentTargetArn": "*", "AssessmentTargetName": "$AssessmentTargetName" },
     "metricName": "TotalFindings",
     "namespace": "AWS/Inspector",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TotalMatchingAgents / TotalHealthyAgents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "AssessmentTargetArn": "*", "AssessmentTargetName": "$AssessmentTargetName" },
     "metricName": "TotalMatchingAgents",
     "namespace": "AWS/Inspector",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "AssessmentTargetArn": "*", "AssessmentTargetName": "$AssessmentTargetName" },
     "metricName": "TotalHealthyAgents",
     "namespace": "AWS/Inspector",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "TotalAssessmentRuns",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "AssessmentTargetArn": "*", "AssessmentTargetName": "$AssessmentTargetName" },
     "metricName": "TotalAssessmentRuns",
     "namespace": "AWS/Inspector",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/inspector/latest/userguide/using-cloudwatch.html\">AWS CloudWatch Inspector documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/14391\">Installed from Grafana.com dashboards</a>\n"
   }
  }
 ]
}