{
 "title": "AWS DynamoDB",
 "description": "Visualize AWS DynamoDB metrics",
 "tags": [
  "cloudwatch",
  "monitoringartist"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "agg", "label": "Aggregation", "query": "30s,1m,5m,15m,1h,6h,1d,7d,30d" },
   { "name": "region", "label": "Region" },
   {
    "name": "tablename",
    "label": "TableName",
    "query": {}
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {}
   },
   {
    "name": "streamlabel",
    "label": "StreamLabel",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "AccountMaxReads/AccountMaxWrites",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountMaxReads",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountMaxWrites",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "AccountMaxTableLevelReads/AccountMaxTableLevelWrites",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountMaxTableLevelReads",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountMaxTableLevelWrites",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "AccountProvisionedReadCapacityUtilization/AccountProvisionedWriteCapacityUtilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountProvisionedReadCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AccountProvisionedWriteCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ConsumedReadCapacityUnits/ConsumedWriteCapacityUnits/ConsumedChangeDataCaptureUnits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "ConsumedChangeDataCaptureUnits",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ConsumedChangeDataCaptureUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "MaxProvisionedTableReadCapacityUtilization/AccountProvisionedWriteCapacityUtilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "MaxProvisionedTableReadCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "MaxProvisionedTableWriteCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "ProvisionedReadCapacityUnits/ProvisionedWriteCapacityUnits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "UserErrors/SystemErrors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "UserErrors",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ThrottledRequests/ReadThrottleEvents/WriteThrottleEvents/ThrottledPutRecordCount/OnlineIndexThrottleEvents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ThrottledPutRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SuccessfulRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{metric}} {{Operation}}",
     "dimensions": { "Operation": "$operation", "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PendingReplicationCount/ReplicationLatency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ReplicationLatency",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "PendingReplicationCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "FailedToReplicateRecordCount/ReplicationLatency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "FailedToReplicateRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "AgeOfOldestUnreplicatedRecord",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "OnlineIndexConsumedWriteCapacity/OnlineIndexPercentageProgress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "OnlineIndexConsumedWriteCapacity",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "OnlineIndexPercentageProgress",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TransactionConflict/TimeToLiveDeletedItemCount/ConditionalCheckFailedRequests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "TransactionConflict",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ConditionalCheckFailedRequests",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ReturnedBytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "Operation": "$operation", "StreamLabel": "$streamlabel", "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ReturnedBytes",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ReturnedItemCount/ReturnedRecordsCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "Operation": "$operation", "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "Operation": "$operation", "StreamLabel": "$streamlabel", "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "ReturnedRecordsCount",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html\">AWS CloudWatch DynamoDB documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/17741\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}