{
 "title": "Application Status Count",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "dev, qa" }
  ]
 },
 "panels": [
  {
   "title": "5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=~\"$namespace\", stream=\"stderr\"} |~ \"HTTP/1.1\\\" 5[0-9][0-9]\" [$__range])"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=~\"$namespace\",stream=\"stderr\"} |~ \"HTTP/1.1\\\" 4[0-9][0-9]\" [$__range])"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=~\"$namespace\", stream=\"stderr\"} |~ \"HTTP/1.1\\\" 2[0-9][0-9]\" [$__range])"
    }
   ]
  },
  {
   "title": "5xx Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=\"stderr\"} |~ \"HTTP/1.1\\\" 5[0-9][0-9]\""
    }
   ]
  },
  {
   "title": "4xx Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=\"stderr\"} |~ \"HTTP/1.1\\\" 4[0-9][0-9]\""
    }
   ]
  },
  {
   "title": "2xx Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\",stream=\"stderr\"} |~ \"HTTP/1.1\\\" 2[0-9][0-9]\""
    }
   ]
  }
 ]
}