{
 "title": "Kafka Dashboard",
 "description": "Kafka resource usage and consumer lag overview",
 "tags": [ "Kafka" ],
 "time": { "from": "2023-07-27T10:14:38.642Z", "to": "2023-07-27T10:24:38.642Z" },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_total_leadercount_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Offline Partitions",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Active Controllers",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Under Replicated Partitions",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_underreplicatedpartitions_value{job=\"kafka-jmx-metrics\"})"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(kafka_server_replicamanager_total_underreplicatedpartitions_value)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum without(instance)(kafka_server_brokertopicmetrics_bytesinpersec_count{topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(kafka_server_brokertopicmetrics_bytesoutpersec_count{topic!=\"\"})\r\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(kafka_server_brokertopicmetrics_total_messagesinpersec_count{job=\"kafka-jmx-metrics\",topic=\"\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum without(instance)(kafka_server_brokertopicmetrics_messagesinpersec_count{job!=\"\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_sessionexpirelistener_total_zookeeperexpirespersec_count{job=\"kafka-jmx-metrics\",instance!=\"\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_sessionexpirelistener_total_zookeeperdisconnectspersec_count{job=\"kafka-jmx-metrics\",instance!=\"\"}[1m]))by(instance)\r\n",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_total_zookeeperrequestlatencyms_count{job=\"kafka-jmx-metrics\",instance!=\"\"})by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  }
 ]
}