{
 "title": "NGINX / API / Host",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_count,host)"
    }
   },
   {
    "name": "Url",
    "label": "url",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_count,endpoint)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ERROR",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by(host) ",
     "legendFormat": "4XX - 1min"
    },
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m])) by(host) ",
     "legendFormat": "5XX - 1min"
    },
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m])) by(host) ",
     "legendFormat": "3XX - 1min"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}\"}[5m])) by (host)",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"50[^3]{1}|5[^0]{1}\"}[5m])) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"30[^3]{1}|3[^0]{1}\"}[5m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{status=~\"2..\",host=~\"$host\"}[5m]))/ sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"2..\",host=~\"$host\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{status=~\"4..\",host=~\"$host\"}[5m]))/ sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"4..\",host=~\"$host\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{status=~\"5..\",host=~\"$host\"}[5m]))/ sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5..\",host=~\"$host\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Successful Requests per Minute per Host",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (host) (\r\n  rate(nginx_ingress_controller_requests{status=~\"2.*\", host=~\"$host\"}[$__range]) * 60\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Client Errors (4xx) by Host (per Minute)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (host) (\r\n  rate(nginx_ingress_controller_requests{status=~\"4.*\", host=~\"$host\"}[$__range]) * 60\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Server Errors (5xx) by Host (per Minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host) (\r\n  rate(nginx_ingress_controller_requests{status=~\"5.*\", host=~\"$host\"}[$__range]) * 60\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status=~\"2..\"}[5m])) by (le, endpoint))",
     "legendFormat": "2XX-P999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status=~\"2..\"}[5m])) by (le, endpoint))",
     "legendFormat": "2XX-P99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status=~\"2..\"}[5m])) by (le, endpoint))",
     "legendFormat": "2XX-avg"
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOP 10 QPS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint, host) (\r\n  rate(nginx_ingress_controller_request_duration_seconds_sum{host=~\"$host\"}[$__range])\r\n) \r\n/\r\nsum by (endpoint, host) (\r\n  rate(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\"}[$__range])\r\n)\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 4XX over 10min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (endpoint)(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[10m]))>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX over 10min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (endpoint)(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[10m]))>0)"
    }
   ]
  }
 ]
}