{
 "title": "Nifi_Metrics",
 "description": "This dashboard is used to monitor the metrics related to NiFi ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "branch",
    "query": {
     "query": "label_values(pushgateway_build_info,branch)"
    }
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "goversion",
    "query": {
     "query": "label_values(pushgateway_build_info,goversion)"
    }
   },
   {
    "name": "revision",
    "query": {
     "query": "label_values(pushgateway_build_info,revision)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pushgateway_build_info,version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "go_gc_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.25\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.25\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.5\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.75\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.75\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"1\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"1\"}"
    },
    {
     "expr": "go_gc_duration_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "go_gc_duration_seconds_count"
    },
    {
     "expr": "go_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "go_gc_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go_goroutines"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_alloc_bytes"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_alloc_bytes_total"
    }
   ]
  },
  {
   "title": "go_memstats_gc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_gc_cpu_fraction"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_gc_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_objects{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_objects"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_mallocs/mcache/mspan",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mallocs_total"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_stack",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Other metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_frees_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_frees_total"
    },
    {
     "expr": "go_memstats_last_gc_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_last_gc_time_seconds"
    },
    {
     "expr": "go_memstats_lookups_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_lookups_total"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_other_sys_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_sys_bytes"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go_threads"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_http_requests_total{code=\"200\",handler=\"/-/healthy\",instance=~\"$instance\"}\t",
     "legendFormat": "prometheus_http_requests_total{code=\"200\",handler=\"/-/healthy\"}\t"
    },
    {
     "expr": "prometheus_http_requests_total{code=\"200\",handler=\"/-/ready\",instance=~\"$instance\"}\t",
     "legendFormat": "prometheus_http_requests_total{code=\"200\",handler=\"/-/ready\"}\t"
    },
    {
     "expr": "prometheus_http_requests_total{code=\"200\",handler=\"/-/reload\",instance=~\"$instance\"}\t",
     "legendFormat": "prometheus_http_requests_total{code=\"200\",handler=\"/-/reload\"}\t"
    }
   ]
  },
  {
   "title": "prometheus_http_response_size_bytes_bucket{le=\"100\"}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_http_response_size_bytes_bucket{handler=~\"/-/healthy\",instance=~\"$instance\",le=\"100\"}\t",
     "legendFormat": "{handler=\"/-/healthy\"}\t"
    },
    {
     "expr": "prometheus_http_response_size_bytes_bucket{handler=~\"/-/ready\",instance=~\"$instance\",le=\"100\"}\t",
     "legendFormat": "{handler=\"/-/ready\", }\t"
    },
    {
     "expr": "prometheus_http_response_size_bytes_bucket{handler=\"/-/reload\",instance=~\"$instance\",le=\"100\"}\t",
     "legendFormat": "{handler=\"/-/reload\"}\t"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=~\"$instance\"}\t",
     "legendFormat": "process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "process_metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}\t",
     "legendFormat": "process_max_fds"
    },
    {
     "expr": "process_open_fds{instance=~\"$instance\"}\t",
     "legendFormat": "process_open_fds"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}\t",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}\t",
     "legendFormat": "process_start_time_seconds"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}\t",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "pushgateway_build_info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pushgateway_build_info{branch=\"$branch\",goversion=\"$goversion\",instance=~\"$instance\",revision=\"$revision\",version=\"$version\"}\t",
     "legendFormat": "pushgateway_build_info"
    }
   ]
  }
 ]
}