{
 "title": "Kubernetes / Compute Resources / Node (Groups)",
 "description": "Grafana dashboard to monitoring nodes grouped by AWS EKS nodegroup. Bear in mind you need a kubernetes label called \"nodegroup\" in each compute < Node Groups",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "nodegroup",
    "query": {
     "query": "label_values(kube_node_labels, label_eks_amazonaws_com_nodegroup)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup =~ \"$nodegroup\"}, node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_info{node =~ \"$node\"}, host_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Node Capacity Type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_eks_amazonaws_com_capacity_type) (kube_node_labels{label_eks_amazonaws_com_capacity_type!=\"\",label_eks_amazonaws_com_nodegroup=\"$nodegroup\", node=\"$node\"})",
     "legendFormat": "{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Nodes Types",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_beta_kubernetes_io_instance_type) (kube_node_labels{label_beta_kubernetes_io_instance_type!=\"\",label_eks_amazonaws_com_nodegroup=\"$nodegroup\",job=\"kube-state-metrics\", node=\"$node\"})",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Pod Count - Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_info{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Pod Count  - Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kubelet_running_pods{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Pod Count - Not Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_info{node=~\"$node\"}) - sum(kubelet_running_pods{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"idle\"}[5m])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$instance:9100\"}[5m])) by (instance))) * 100",
     "legendFormat": "{{instance}}-cpu-utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"}) / node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} * 100",
     "legendFormat": "{{instance}}-memory-utilization"
    }
   ]
  },
  {
   "title": "CPU Info on Node (in m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=\"$node\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node=\"$node\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"$node\", cpu=\"total\"}[$__rate_interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(machine_cpu_cores{node=\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Info on Node (in GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=\"$node\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", node=\"$node\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "machine_memory_bytes{node=\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{instance=~\"$instance:9100\"}) by (instance) - sum (node_filesystem_free_bytes{instance=~\"$instance:9100\"}) by (instance)) / sum (node_filesystem_size_bytes{instance=~\"$instance:9100\"}) by (instance) * 100",
     "legendFormat": "{{kubernetes_node}}-disk-utilization"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$instance:9100\"}[5m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-read-bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$instance:9100\"}[5m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-write-bytes"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance:9100\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-network-in"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance:9100\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (instance)",
     "legendFormat": "{{instance}}-network-out"
    }
   ]
  },
  {
   "title": "Load Avg (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (15m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}