{
 "title": "Thanos / Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Querier, Query-Frontend, Compacter and Store.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count\n(\n  kube_pod_container_info{container=~\"thanos.*|query.*|storegateway.*|compactor.*|bucketweb.*\"}\n) by (container)\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Thanos / Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} REQUESTS"
    },
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\"}) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\"}) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\", container=~\"query.*\", container!~\"query-frontend.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod!~\"thanos-query-frontend.*\", pod=~\"thanos-query-.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\", container=~\"query-frontend.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"query-frontend.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} REQUESTS"
    },
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",  container=~\"query-frontend.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"query-frontend.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\", container=~\"query-frontend.*\"}) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"query-frontend.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\",  container=~\"query-frontend.*\"}) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"query-frontend.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-query-frontend.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Compact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\", container=~\"compactor.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"compactor.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} REQUESTS"
    },
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",  container=~\"compactor.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"compactor.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\", container=~\"compactor.*\"}) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"compactor.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\",  container=~\"compactor.*\"}) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"compactor.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-compactor.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\", container=~\"storegateway.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"storegateway.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} REQUESTS"
    },
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",  container=~\"storegateway.*\"}[$__interval])) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"storegateway.*\", resource=\"cpu\"})",
     "legendFormat": "{{container}} LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\", container=~\"storegateway.*\"}) / sum by(container) (kube_pod_container_resource_requests{namespace=\"monitoring\", container=~\"storegateway.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"monitoring\",  container=~\"storegateway.*\"}) / sum by(container) (kube_pod_container_resource_limits{namespace=\"monitoring\",  container=~\"storegateway.*\", resource=\"memory\"})",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-storegateway.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    thanos_store_index_cache_hits_total[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    thanos_store_index_cache_requests_total[$__rate_interval]\n  ) \n)",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(thanos_store_index_cache_hits_total[5m])",
     "legendFormat": "{{item_type}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "bucket_store_cached_series_fetch_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(thanos_bucket_store_cached_series_fetch_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}